### ISSUE TITLE
Timeshift 19.08.1 does not apply file/folder exclude/include settings

### ISSUE THREAD

**Issue by Auronius** [teejee2008/timeshift#496]
**Describe the bug**
When I add folder or file to exclude/include list, Timeshift 19.08.1 does not apply exclude/include settings. When I open exclude/include settings page again, my settings are reverted to defaults. This problem was not in previous Timeshift releases.

**Please watch this video**
https://drive.google.com/open?id=14XscQVr6eDMcSavs7bJDBmfTg8fyl5TB

**To Reproduce**
1. Go to Filters -> add file or folder in Include/Exclude list
2. Change include/exclude setting -> click OK
3. Open Settings -> Filters again
4. Your include/exclude setting will not be saved

**Application version**
https://drive.google.com/open?id=14UmEdSL-jlH5tMsWm8OPZxoieMyt81fZ

**System**
https://drive.google.com/open?id=1zzNSFU870dx0oLVd7JoLwsvFfiyHanfG

Please help! I can not make proper system backups because of this problem :(

**Update:** On another PC I have exactly the same problem.
https://user-images.githubusercontent.com/13540006/67145855-d0dd8600-f28d-11e9-9a5c-a080f4c21be9.png

**Comment by Auronius** [comment]
I have installed [an older version v19.01](https://github.com/teejee2008/timeshift/releases/download/v19.01/timeshift-v19.01-i386.deb), and this version remembers folder exclude/include settings, but does not remember file settings.
https://drive.google.com/open?id=14mDGKfJXyMAMzzryqrpaizKzeLgsJZG1
https://drive.google.com/open?id=1Qw3uzsAxo_yusCYYGfc3xSlWz2FXmCcC

**Comment by FloatingRain** [comment]
I got this problem too.

**Comment by FloatingRain** [comment]
I've got this problem too. Just like the picture, there seem to be a terrible problem: after more than six rules have been added, the rule, whcih be added last, its' order in the entry and "+/-" will never be saved correctly ,  it will only locate at last position and be "-".

Please check codes here @teejee2008 .

![](https://pic1.superbed.cn/item/5dd5392f8e0e2e3ee95ed753.jpg)

**Comment by Auronius** [comment]
It is an important problem. I was forced to restore my Desktop and reinstall SoftMaker Office, because needed folders have not been restored. But I clearly remember, that I have included (+) them in list.
After that, I rolled back to Timeshift 19.01. https://github.com/teejee2008/timeshift/releases/tag/v19.01
I hope, it will be fixed soon.

**Comment by gabridoppiozero** [comment]
I managed to include all the files that I wanted by sudo-editing the timeshift config file /etc/timeshift.json, and in the timeshift-launcher the options were set correctly. However, from the launcher, I couldn't edit the ones that I've entered manually in the config file. It seems it lacks some sort of permission...

**Comment by jan-eri** [comment]
I found this thread after experiencing the same problem on Timeshift 19.08 on Linux Mint 19.3 just now.

**Comment by bbolyasov** [comment]
Exclusion list saves if I use 'close' button instead of 'ok'.

**Comment by floatingrain** [comment]
this bug seems has been fixed, you can close this issue.

**Comment by Auronius** [comment]
> this bug seems has been fixed, you can close this issue.

In which release version this has been fixed? I still use v.19.01 because of this bug in newer releases.

**Comment by floatingrain** [comment]
> > this bug seems has been fixed, you can close this issue.
> 
> In which release version this has been fixed? I still use v.19.01 because of this bug in newer releases.

I'm using v20.03, and it apply my exclude/include settings now.

**Comment by sl5net** [comment]
I'm using v20.03, and I got this problem too. Reported first here: https://askubuntu.com/questions/1282194/timeshift-v20-deletes-my-changes-in-settings-filters

**Comment by floatingrain** [comment]
> I'm using v20.03, and I got this problem too. Reported first here: https://askubuntu.com/questions/1282194/timeshift-v20-deletes-my-changes-in-settings-filters

maybe you should try reinstall timeshift

**Comment by sl5net** [comment]
Not solved. Of course I tried reinstalling it. And later I installed a new linux first. Same problem. Did you tried it (with same configuration)?

**Comment by floatingrain** [comment]
> Not solved. Of course I tried reinstalling it. And later I installed a new linux first. Same problem. Did you tried it (with same configuration)?

I used Manjaro Linux before, and Timeshift has this bug. But after I switch to Ubuntu, it disappeared. I think this bug is complicated, it may be related to Linux distributions.

**Comment by Zackhardtoname** [comment]
There has been a workaround. It has worked for me on Arch and Manjaro.
Just in case you have not seen it - the last few posts here: https://forums.linuxmint.com/viewtopic.php?t=285111

Essentially you need to:

> change users to exclude all
change order
change users to include all

**Comment by Auronius** [comment]
This has been fixed in **Timeshift 20.11.1.** At least I am unable to reproduce this bug anymore.

**Comment by GienekWspanialy** [comment]
It's not fixed, at least not in my case. I'm also on Timeshift 20.11.1 (Manjaro 20.2). @Zackhardtoname the workaround that you mentioned is not given in the link that you posted (I think). Could you clarify how to change order of the rules? I mean, is there some specific order that works as a workaround or just any shuffling works?

**Comment by Zackhardtoname** [comment]
> It's not fixed, at least not in my case. I'm also on Timeshift 20.11.1 (Manjaro 20.2). @Zackhardtoname the workaround that you mentioned is not given in the link that you posted (I think). Could you clarify how to change order of the rules? I mean, is there some specific order that works as a workaround or just any shuffling works?

Sorry I have corrected the link. Could you try again?

**Comment by GienekWspanialy** [comment]
@Zackhardtoname Yes, the workaround resolved the issue. Thank you :)

**Comment by Innovator42** [comment]
STILL not fixed.  I have 19.08.1.2+tricia, which is the latest version iaccording to Synaptic Pkg Manager.  I'd like to upgrade from LM 19.3 to 20.X, but will not do so unless I can backup the system - which is not possible unless I can exclude some very large files.  Excluding files worked previously.  Is this what I get for updating?
