### ISSUE TITLE
Critical error when copying.

### ISSUE THREAD

**Issue by imLEGR** [teejee2008/timeshift#937]
**Describe the bug**
There are bugs in the operation of the program. First, it stopped showing the remaining time, just three question marks. Now the GUI crashes when copying and deleting, but the process itself on the system continues.

**To Reproduce**
1. I open the program.
2. I start copying rsync.
3. After a while, the program window closes abruptly.

It also says "???" instead of the remaining time.

**Expected behavior**
I expected the copying to be successful.

Log file:
https://pastebin.com/FtQ4aqqE
[Timeshift log.txt](https://github.com/teejee2008/timeshift/files/9639037/Timeshift.log.txt)

**System:**
 - Arch Linux
 - KDE Plasma
 - Application Version 22.06.5

**Comment by attishno1** [comment]
The GUI is also not detecting snapshots anymore either.

**Comment by cimarronline** [comment]
Looks like this might be caused by the recent update to glib2 2.74.0-1:
https://forum.manjaro.org/t/timeshift-gtk-dumps-core/122478

**Comment by imLEGR** [comment]
> Looks like this might be caused by the recent update to glib2 2.74.0-1: https://forum.manjaro.org/t/timeshift-gtk-dumps-core/122478
> 
> Apparently downgrading glib2 restores proper functionality. Also, timeshift cli seems unaffected.

Yes, cli Timeshift fortunately still works, but the remaining time there is also not shown. I wish they would fix the GUI too. I don't want to roll something back because other components might stop working.

Do you know if Timeshift is still being developed?

**Comment by yochananmarqos** [comment]
> Do you know if Timeshift is still being developed?

See the Note at the top of the [README](https://github.com/teejee2008/timeshift#readme).

**Comment by imLEGR** [comment]
> > Do you know if Timeshift is still being developed?
> 
> See the Note at the top of the [README](https://github.com/teejee2008/timeshift#readme).

Can you tell me how I can put that fork on Arch Linux? I must be doing something wrong. And as I understand it's not very actively developed there either.

**Comment by yochananmarqos** [comment]
It already is via the `timeshift` AUR package. The Manjaro community package uses it as well.

**Comment by imLEGR** [comment]
> It already is via the `timeshift` AUR package. The Manjaro community package uses it as well.

So this error should be written to the Linux Mint fork. So this error should be written to the Linux Mint fork. Strange, I thought AUR installs from here.

**Comment by attishno1** [comment]
The CLI gets stuck at 0.0%. I mean the timeshift still creates a snapshot but the progress is stuck at 0.0% on CLI

**Comment by cimarronline** [comment]
I suspect it's a problem with glib2 2.74.0. There are other reports of random crashes, and one fix has already been merged. But Timeshift seems to be still affected (the crashes seem random).

https://gitlab.gnome.org/GNOME/glib/-/issues/2770

**Comment by teejee2008** [comment]
This is fixed

**Comment by cimarronline** [comment]
Thanks! Works great for me with glib2 2.74.

**Comment by imLEGR** [comment]
> This is fixed
The time to the end of the operation and the progress still does not show.

![2022-10-15_22-52-01](https://user-images.githubusercontent.com/53097257/196005433-5ec13759-ceb9-4f4f-8596-b90c63bfc036.png)
